package flory.FloryServer.domain.enums;

public enum FlowerMeaning {
    HAPPINESS, UNREST, FLUTTER, EMBARRASSMENT, FRIENDSHIP, INTERSET,
    JEALOUSY, HOPE, PASSION, CRUSH, CHEER, MISS, TIRED, DISAPPOINTMENT,
    HATE, LONELY, PAIN, HESITATE
}
